services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql/data
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DB: mysql
      # (this is just an example, not intended to be a production configuration)

